defmodule Muhurta.Repo.Migrations.EventPublish do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:ticket_purchases) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :rsvp_date
    # 
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :rsvp_status
    # end
    # 
    alter table(:events) do
      add :is_published, :boolean, default: false
    end
  end

  def down do
    alter table(:events) do
      remove :is_published
    end

    # alter table(:ticket_purchases) do
    # This is the `down` migration of the statement:
    #
    #     remove :rsvp_status
    #
    # 
    # add :rsvp_status, :text
    # This is the `down` migration of the statement:
    #
    #     remove :rsvp_date
    #
    # 
    # add :rsvp_date, :utc_datetime
    # end
    # 
  end
end
