defmodule Muhurta.Repo.Migrations.InstallAshMoneyV220240425083431 do
  @moduledoc """
  Installs any extensions that are mentioned in the repo's `installed_extensions/0` callback

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute """
    CREATE OR REPLACE FUNCTION money_mult(multiplicator numeric, money money_with_currency)
    RETURNS money_with_currency
    IMMUTABLE
    STRICT
    LANGUAGE plpgsql
    AS $$
      DECLARE
        currency varchar;
        multiplication numeric;
      BEGIN
          currency := currency_code(money);
          multiplication := amount(money) * multiplicator;
          return row(currency, multiplication);
      END;
    $$;
    """

    execute """
    CREATE OR REPLACE FUNCTION money_mult_reverse(money money_with_currency, multiplicator numeric)
    RETURNS money_with_currency
    IMMUTABLE
    STRICT
    LANGUAGE plpgsql
    AS $$
    BEGIN
        RETURN money_mult(multiplicator, money);
    END;
    $$;
    """

    execute """
    CREATE OPERATOR * (
        LEFTARG = numeric,
        RIGHTARG = money_with_currency,
        PROCEDURE = money_mult
    );
    """

    execute """
    CREATE OPERATOR * (
        LEFTARG = money_with_currency,
        RIGHTARG = numeric,
        PROCEDURE = money_mult_reverse
    );
    """
  end

  def down do
    # Uncomment this if you actually want to uninstall the extensions
    # when this migration is rolled back:
    execute "DROP OPERATOR * (money_with_currency, numeric);"
    execute "DROP OPERATOR * (numeric, money_with_currency);"

    execute "DROP FUNCTION IF EXISTS money_mult(multiplicator numeric, money money_with_currency);"

    execute "DROP FUNCTION IF EXISTS money_mult(money money_with_currency, multiplicator numeric);"

    execute "DROP AGGREGATE IF EXISTS sum(money_with_currency);"

    execute "DROP FUNCTION IF EXISTS money_sum_combine_function(agg_state1 money_with_currency, agg_state2 money_with_currency);"

    execute "DROP FUNCTION IF EXISTS money_sum_state_function(agg_state money_with_currency, money money_with_currency);"

    execute "DROP AGGREGATE IF EXISTS max(money_with_currency);"

    execute "DROP FUNCTION IF EXISTS money_max_combine_function(agg_state1 money_with_currency, agg_state2 money_with_currency);"

    execute "DROP FUNCTION IF EXISTS money_max_state_function(agg_state money_with_currency, money money_with_currency);"

    execute "DROP AGGREGATE IF EXISTS min(money_with_currency);"

    execute "DROP FUNCTION IF EXISTS money_min_combine_function(agg_state1 money_with_currency, agg_state2 money_with_currency);"

    execute "DROP FUNCTION IF EXISTS money_min_state_function(agg_state money_with_currency, money money_with_currency);"

    execute "DROP OPERATOR + (money_with_currency, money_with_currency);"

    execute "DROP FUNCTION IF EXISTS money_add(money_1 money_with_currency, money_2 money_with_currency);"

    execute "DROP TYPE public.money_with_currency;"
  end
end
